"use client";
import {useEffect,useMemo,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import Header from "@/components/Header";
import VideoInspiredTemplate from "@/components/templates/VideoInspiredTemplate";
import TeatroInspiredTemplate from "@/components/templates/TeatroInspiredTemplate";
import InvitationTheme from "@/components/InvitationTheme";
import {defaultInvitation,InvitationData,SectionKey} from "@/lib/invitation";
import {templates,Template} from "@/lib/templates";

const labels:Record<SectionKey,string>={story:"القصة والنص",schedule:"التاريخ والوقت",gallery:"معرض الصور",venue:"المكان والخريطة",rsvp:"تأكيد الحضور",wishes:"التهاني"};
const palettes=[
 {name:"ذهبي",accent:"#9a7650",background:"#fbfaf8"},{name:"وردي",accent:"#b76e79",background:"#fff7f7"},
 {name:"أخضر",accent:"#71816b",background:"#f7f8f3"},{name:"ليلي",accent:"#b89468",background:"#171215"}
];

export default function CreatePage(){
 const params=useParams<{templateId:string}>(); const router=useRouter();
 const [template,setTemplate]=useState<Template|null>(null);
 const [templateLoading,setTemplateLoading]=useState(true);
 const fallback=templates.find(t=>t.id===params.templateId)??templates[0];
 const [data,setData]=useState<InvitationData>({...defaultInvitation,templateId:params.templateId,sections:{...defaultInvitation.sections},sectionOrder:defaultInvitation.sectionOrder});
 const supported=template?.supportedSections ?? fallback.supportedSections ?? ["story","schedule","gallery","venue","rsvp","wishes"];
 const visibleSectionOrder=data.sectionOrder.filter(key=>supported.includes(key));
 const [tab,setTab]=useState<"content"|"design"|"sections">("content"); const [saved,setSaved]=useState(false); const [dragging,setDragging]=useState<SectionKey|null>(null);
 useEffect(()=>{ fetch(`/api/templates`).then(r=>r.json()).then(list=>{const found=Array.isArray(list)?(list as Template[]).find(x=>x.id===params.templateId):null; if(found){setTemplate(found);setData(d=>({...d,templateId:found.id,sectionOrder:d.sectionOrder.filter(k=>(found.supportedSections ?? []).includes(k))}));} else {setTemplate(null);} }).finally(()=>setTemplateLoading(false)); },[params.templateId]);
 useEffect(()=>{const slug=new URLSearchParams(window.location.search).get("slug"); if(!slug)return; fetch(`/api/invitations?slug=${encodeURIComponent(slug)}&mine=1`).then(r=>r.ok?r.json():null).then(x=>x?.ownerId&&setData(x)).catch(()=>{});},[]);
 const update=<K extends keyof InvitationData>(key:K,value:InvitationData[K])=>{setSaved(false);setData(d=>({...d,[key]:value}))};
 const updateDesign=<K extends keyof InvitationData["design"]>(key:K,value:InvitationData["design"][K])=>{setSaved(false);setData(d=>({...d,design:{...d.design,[key]:value}}));};
 const toggle=(key:SectionKey)=>{setSaved(false);setData(d=>({...d,sections:{...d.sections,[key]:!d.sections[key]}}));};
 const move=(from:SectionKey,to:SectionKey)=>{setSaved(false);setData(d=>{const order=[...d.sectionOrder];const a=order.indexOf(from),b=order.indexOf(to);if(a<0||b<0)return d;order.splice(a,1);order.splice(b,0,from);return {...d,sectionOrder:order};});};
 const save=async()=>{const slug=data.slug.trim().toLowerCase().replace(/\s+/g,"-");const next={...data,slug:slug||"دعوة"};const r=await fetch("/api/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(r.status===401){router.push(`/login?next=/create/${encodeURIComponent(params.templateId)}`);return}const x=await r.json();if(!r.ok){alert(x.error||"تعذر الحفظ");return}setData(x);setSaved(true)};
 const formatted=useMemo(()=>data.date?new Intl.DateTimeFormat("ar-JO",{dateStyle:"long",timeStyle:"short"}).format(new Date(`${data.date}T${data.time||"20:00"}`)):"",[data.date,data.time]);

 if(templateLoading) return <main className="min-h-screen grid place-items-center">جارٍ تحميل القالب…</main>;
 if(!template) return <main className="min-h-screen grid place-items-center p-6 text-center"><div><h1 className="serif text-4xl">القالب غير متاح</h1><p className="mt-3 text-[#756f68]">تم إخفاء هذا القالب أو أنه غير موجود.</p><button className="btn btn-primary mt-6" onClick={()=>router.push("/templates")}>العودة للقوالب</button></div></main>;
 const preview=<InvitationTheme data={data}>{template.id==="teatro-inspired"?<TeatroInspiredTemplate groom={data.groom} bride={data.bride} date={formatted} venue={data.venue} address={data.address} invitationText={data.invitationText} heroImage={data.heroImage} mapUrl={data.mapUrl} videoUrl={data.videoUrl} musicUrl={data.musicUrl} rsvpEnabled={data.rsvpEnabled} monogram={data.monogram} gallery={data.gallery} sections={data.sections} sectionOrder={data.sectionOrder}/>:template.style==="video"?<VideoInspiredTemplate variant={data.templateId} groom={data.groom} bride={data.bride} date={formatted} venue={data.venue} invitationText={data.invitationText} heroImage={data.heroImage} eventDate={data.date} eventTime={data.time} mapUrl={data.mapUrl} musicUrl={data.musicUrl} videoUrl={data.videoUrl} rsvpEnabled={data.rsvpEnabled} gallery={data.gallery} sections={data.sections} sectionOrder={data.sectionOrder}/>:<div className="rounded-[32px] bg-white min-h-[720px] p-8 flex flex-col items-center justify-center text-center shadow-2xl"><p className="text-xs tracking-[.3em] opacity-60">دعوة خاصة</p><h1 className="serif text-6xl mt-8">{data.groom} <span className="gold">&</span> {data.bride}</h1><p className="mt-6">{formatted}</p><p className="text-sm text-[#756f68] mt-2">{data.venue}</p></div>}</InvitationTheme>;
 return <><Header/><main className="section"><div className="container"><div className="editor-head"><div><p className="gold text-sm font-bold">V12 · استوديو الدعوة</p><h1 className="serif text-4xl mt-2">صمّم دعوتك كما تريد</h1><p className="text-sm text-[#756f68] mt-2">عدّل المحتوى، الهوية، وترتيب الأقسام مع معاينة فورية.</p></div><div className="flex gap-2"><button className="btn btn-light" onClick={()=>window.open(`/i/${encodeURIComponent(data.slug)}`,"_blank")}>فتح الدعوة</button><button className="btn btn-primary" onClick={save}>{saved?"تم الحفظ ✓":"حفظ ونشر"}</button></div></div>
 <div className="grid xl:grid-cols-[400px_1fr] gap-8 items-start mt-8"><aside className="editor-panel"><div className="editor-tabs">{[["content","المحتوى"],["design","التصميم"],["sections","الأقسام"]].map(([id,l])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id as "content"|"design"|"sections")}>{l}</button>)}</div>
 {tab==="content"&&<div className="space-y-4"><Field label="الاسم الأول" value={data.groom} onChange={v=>update("groom",v)}/><Field label="الاسم الثاني" value={data.bride} onChange={v=>update("bride",v)}/><div className="grid grid-cols-2 gap-3"><Field label="التاريخ" type="date" value={data.date} onChange={v=>update("date",v)}/><Field label="الوقت" type="time" value={data.time} onChange={v=>update("time",v)}/></div><Field label="المكان" value={data.venue} onChange={v=>update("venue",v)}/><Field label="العنوان" value={data.address} onChange={v=>update("address",v)}/><Field label="رابط الخريطة" value={data.mapUrl} onChange={v=>update("mapUrl",v)} placeholder="Google Maps"/><Field label="صورة الغلاف" value={data.heroImage} onChange={v=>update("heroImage",v)} placeholder="رابط الصورة"/><Field label="الفيديو" value={data.videoUrl} onChange={v=>update("videoUrl",v)} placeholder="رابط الفيديو"/><Field label="الموسيقى" value={data.musicUrl} onChange={v=>update("musicUrl",v)} placeholder="رابط MP3"/><label className="field-label">نص الدعوة<textarea className="field resize-none" rows={4} value={data.invitationText} onChange={e=>update("invitationText",e.target.value)}/></label><Field label="الشعار / الأحرف" value={data.monogram} onChange={v=>update("monogram",v)}/><Field label="الرابط المختصر" value={data.slug} onChange={v=>update("slug",v)} placeholder="mohammad-lina"/><label className="switch-row"><span>تفعيل RSVP</span><input type="checkbox" checked={data.rsvpEnabled} onChange={e=>update("rsvpEnabled",e.target.checked)}/></label></div>}
 {tab==="design"&&<div><h3 className="editor-section-title">لوحات جاهزة</h3><div className="palette-grid">{palettes.map(p=><button key={p.name} className="palette" onClick={()=>{updateDesign("accent",p.accent);updateDesign("background",p.background)}}><span style={{background:p.accent}}/><b>{p.name}</b></button>)}</div><label className="field-label">اللون الأساسي<div className="color-row"><input type="color" value={data.design.accent} onChange={e=>updateDesign("accent",e.target.value)}/><input className="field" value={data.design.accent} onChange={e=>updateDesign("accent",e.target.value)}/></div></label><label className="field-label">لون الخلفية<div className="color-row"><input type="color" value={data.design.background} onChange={e=>updateDesign("background",e.target.value)}/><input className="field" value={data.design.background} onChange={e=>updateDesign("background",e.target.value)}/></div></label><label className="field-label">الخط<select className="field" value={data.design.font} onChange={e=>updateDesign("font",e.target.value as InvitationData["design"]["font"])}><option value="serif">Serif · كلاسيكي</option><option value="sans">Sans · واضح</option><option value="modern">Modern · عصري</option><option value="display">Display · فاخر</option></select></label><label className="field-label">استدارة البطاقات<select className="field" value={data.design.radius} onChange={e=>updateDesign("radius",e.target.value as InvitationData["design"]["radius"])}><option value="soft">ناعمة</option><option value="round">دائرية</option><option value="square">مربعة</option></select></label><label className="field-label">حجم العناوين<select className="field" value={data.design.titleSize} onChange={e=>updateDesign("titleSize",e.target.value as InvitationData["design"]["titleSize"])}><option value="compact">متوسط</option><option value="large">كبير</option></select></label><label className="field-label">قوة طبقة الصورة<input type="range" min="0" max="70" value={data.design.overlay} onChange={e=>updateDesign("overlay",Number(e.target.value))}/></label><button className="btn btn-light w-full mt-4" onClick={()=>setData(d=>({...d,design:{...defaultInvitation.design}}))}>إعادة ضبط التصميم</button></div>}
 {tab==="sections"&&<div><p className="text-sm text-[#756f68] leading-6">اسحب القسم إلى موضع جديد، أو استخدم الأسهم. إخفاء القسم لا يحذف بياناته.</p><div className="section-dnd mt-4">{visibleSectionOrder.map((key,i)=><div key={key} draggable onDragStart={()=>setDragging(key)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragging&&dragging!==key)move(dragging,key);setDragging(null)}} className={`section-sort-row ${dragging===key?"dragging":""}`}><label><span className="drag-grip">⋮⋮</span><input type="checkbox" checked={data.sections[key]} onChange={()=>toggle(key)}/>{labels[key]}</label><div><button disabled={i===0} onClick={()=>move(key,visibleSectionOrder[i-1])}>↑</button><button disabled={i===visibleSectionOrder.length-1} onClick={()=>move(key,visibleSectionOrder[i+1])}>↓</button></div></div>)}</div><div className="editor-tip mt-5"><b>نصيحة</b><p>ضع RSVP بعد معلومات المكان، ومعرض الصور قبل التهاني للحصول على تدفق طبيعي.</p></div></div>}
 </aside><section className="preview-stage"><div className="preview-toolbar"><span>معاينة مباشرة</span><span className="preview-url">/i/{data.slug||"دعوة"}</span></div><div className="preview-device">{preview}</div></section></div></div></main></>;
}
function Field({label,value,onChange,type="text",placeholder}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="field-label">{label}<input className="field" type={type} value={value||""} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
